# Назначение файла: конфигурация Docker Compose для бота и MongoDB.
# Секреты загружаются из `.env` и не хранятся в репозитории.
# Порт хоста можно задать через переменную `HOST_PORT`.
services:
  bot:
    build:
      context: ./bot
    env_file:
      - .env
    environment:
      - BOT_API_URL=${BOT_API_URL}
    restart: always
    depends_on:
      - mongo_db
    ports:
      - "${HOST_PORT:-3000}:${PORT:-3000}"
  mongo_db:
    container_name: task-bot-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
    ports:
      - "27017:27017"
    volumes:
      - mongo_db_example_app:/data/db

volumes:
  mongo_db_example_app:
