# Назначение файла: конфигурация Docker Compose для бота и панели.
services:
  bot:
    build:
      context: ./bot
    env_file:
      - .env
    restart: always
  admin:
    build:
      context: ./admin
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
