# Назначение файла: конфигурация Docker Compose для бота и панели.
# Секреты загружаются из `.env` и не хранятся в репозитории.
services:
  bot:
    build:
      context: ./bot
    env_file:
      - .env
    restart: always
    depends_on:
      - mongo_db
  admin:
    build:
      context: ./admin
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    depends_on:
      - mongo_db
  mongo_db:
    container_name: adminjs-example-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_db_example_app:/data/db

volumes:
  mongo_db_example_app:
