# Docker Compose для запуска бота и панели AdminJS
version: '3.8'
services:
  bot:
    build:
      context: ./bot
    env_file:
      - .env
    restart: always
  admin:
    build:
      context: ./admin
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
