name: "Баг"
description: "Сообщить об ошибке"
title: "[Bug] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Опишите проблему и шаги для воспроизведения.
  - type: textarea
    id: steps
    attributes:
      label: "Шаги"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Ожидаемое поведение"
  - type: textarea
    id: logs
    attributes:
      label: "Логи"
