services:
  mongo_db:
    container_name: adminjs-example-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_db_example_app:/data/db



volumes:
  mongo_db_example_app:
