steps:

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']


  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '$SERVICE_NAME',
      '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
      '--platform', 'managed',
      '--region', '$REGION',
      '--allow-unauthenticated'
    ]

substitutions:
  _SERVICE_NAME: 'nodejs-task-bot-service' 
  _REGION: 'us-central1' 
  _REPO_NAME: 'nodejs-task-bot-repo' 

timeout: '600s' 

