# Назначение файла: базовый workflow для запуска тестов
# Модули: установка зависимостей и выполнение npm test
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Установка зависимостей
        run: ./scripts/install_bot_deps.sh
      - name: Проверка зависимостей (audit-ci)
        run: ./scripts/audit_deps.sh

  lint-test-build:
    runs-on: ubuntu-latest
    needs: audit-deps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Включение corepack
        run: corepack enable
      - name: Установка зависимостей
        run: pnpm install
      - name: Проверка build-скриптов
        run: pnpm approve-builds
      - name: Установка браузеров Playwright
        run: npx playwright install --with-deps
      - name: Линтеры
        run: pnpm lint
      - name: Тесты
        run: pnpm -r test
      - name: Сборка
        run: pnpm -r build
      - name: Проверка размера бандла
        run: pnpm size
