# Назначение файла: базовый workflow для запуска тестов
# Модули: установка зависимостей и выполнение npm test
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Установка зависимостей
        run: ./scripts/install_bot_deps.sh
      - name: Проверка зависимостей
        run: ./scripts/audit_deps.sh
      - name: Тесты и линтеры
        run: ./scripts/setup_and_test.sh
      - name: Сборка клиента
        run: npm --prefix bot run build-client
