# Назначение файла: базовый workflow для запуска тестов
# Модули: установка зависимостей и выполнение npm test
name: CI

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main]

jobs:
  audit-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Установка зависимостей
        run: ./scripts/install_bot_deps.sh
      - name: Проверка зависимостей (audit-ci)
        run: ./scripts/audit_deps.sh

  lint-test-build:
    runs-on: ubuntu-latest
    needs: audit-deps
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Включение corepack
        run: corepack enable
      - name: Установка зависимостей
        run: pnpm install
      - name: Проверка build-скриптов
        run: pnpm approve-builds
      - name: Установка браузеров Playwright
        run: npx playwright install --with-deps
      - name: Линтеры
        run: pnpm lint
      - name: Юнит и API тесты
        run: pnpm test:unit && pnpm test:api
      - name: Сохранение артефактов
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            coverage
            playwright-report
            test-results
      - name: Сборка
        run: pnpm -r build
      - name: Загрузка артефактов сборки
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: apps/api/public
      - name: Проверка размеров бандлов
        run: mkdir -p apps/web/dist && cp -r apps/api/public/assets apps/web/dist/ && pnpm size
      - name: Загрузка sourcemap
        if: github.ref == 'refs/heads/staging'
        uses: actions/upload-artifact@v4
        with:
          name: sourcemaps
          path: apps/api/public/assets/**/*.map

  e2e-tests:
    runs-on: ubuntu-latest
    needs: lint-test-build
    strategy:
      matrix:
        project: [chromium, firefox, webkit, 'Pixel 7', 'iPhone 14']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Включение corepack
        run: corepack enable
      - name: Установка зависимостей
        run: pnpm install
      - name: Установка браузеров Playwright
        run: npx playwright install --with-deps
      - name: E2E тесты
        run: pnpm test:e2e -- --project="${{ matrix.project }}"
      - name: Сохранение артефактов
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.project }}
          path: playwright-report
