# Назначение файла: базовый workflow для запуска тестов
# Модули: установка зависимостей и выполнение npm test
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Установка зависимостей
        run: ./scripts/install_bot_deps.sh
      - name: Установка браузеров Playwright
        run: npx playwright install --with-deps
      - name: Проверка зависимостей (audit-ci)
        run: ./scripts/audit_deps.sh
      - name: Тесты и линтеры
        run: ./scripts/setup_and_test.sh
      - name: Unit тесты с покрытием
        run: pnpm test:unit --coverage
      - name: API тесты
        run: pnpm test:api
      - name: E2E тесты
        run: pnpm test:e2e
      - name: Подготовка клиента
        run: npm run prepare-client
      - name: Проверка контраста
        run: pnpm a11y
